version: '2'
services:
  web:
    build:
      context: core/
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MATCH_URL=http://matching:8080
    ports:
      - "80:8080"
    links:
      - redis
      - matching
    depends_on:
      - redis
      - matching

  matching:
    build:
      context: matching/
      dockerfile: Dockerfile
    expose:
      - "8080"

  redis:
    image: redis:5.0.3
    expose:
      - "6379"

  rcli:
    image: redis:latest
    links:
      - redis
    command: redis-cli -h redis
